# Name of your application. Used to uniquely configure containers.
service: datascience-lab8

# Name of the container image.
image: markalbrand/datascience-lab8

# Deploy to these servers.
servers:
  web:
    - server1.albrand.tech

# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
# If using something like Cloudflare, it is recommended to set encryption mode 
# in Cloudflare's SSL/TLS setting to "Full" to enable end-to-end encryption. 
proxy: 
  ssl: true
  host: ds-l8.albrand.tech
  app_port: 8501

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: markalbrand

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

ssh:
  user: deployer # Server user to connect as (default: root)
  keys: ["~/.ssh/hetzner-access"] # List of SSH keys to use for authentication
